### ISSUE TITLE
Module name in Readme not correct

### ISSUE THREAD

**Issue by RVXD** [hurstindustries/jh-angular-number-picker#1]
Hi, 
thanks for your module.

In the README module name is 'jh-angular-number-picker'
This will throw an error, since the actual name is 'jh.angular-number-picker' with a dot.

Regards.

**Comment by hurstindustries** [comment]
Hey thanks Remy! Will get that rectified today. 

Joshua Hurst

**Comment by hurstindustries** [comment]
Fixed and released
